import "./globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Js",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="min-h-screen bg-black-100 font">{children}</body>
    </html>
  );
}
